spring:
  application:
    name: product-service
  
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/prueba-tecnica
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

logging:
  level:
    com.pruebatecnica.productservice: DEBUG