spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      routes:
        # Auth Service Routes
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        
        # User Service Routes (part of auth-service)
        - id: auth-service-users
          uri: lb://auth-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
        
        # Product Service Routes
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
        
        # Cart Service Routes
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/carts/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
        
        # Order Service Routes
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
        
        # Configuration Routes (can be handled by any service or dedicated config service)
        - id: configuration-service
          uri: lb://product-service  # For now, handled by product-service
          predicates:
            - Path=/api/configuration/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH  
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# JWT Configuration for Gateway filters
jwt:
  secret-key: mySecretKeyForJWTTokenGeneration123456789012345678901234567890

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.pruebatecnica.apigateway: DEBUG